# Generated by Django 5.0.3 on 2025-03-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=245, verbose_name='first name')),
                ('last_name', models.CharField(max_length=245, verbose_name='last name')),
                ('email', models.EmailField(max_length=245, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=245, unique=True, verbose_name='username')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('active', models.BooleanField(default=False, verbose_name='is active')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
